baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'Ensono Stacks SecOps Body of Knowledge'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  disableMermaid = false
  disableMathJax = false
  disableOpenapi = false
  editURL = 'https://github.com/Ensono/stacks-secops-bok/edit/main/content/${FilePath}'
  themeVariant = [ 'auto', 'ensono-light', 'ensono-dark' ]

[parms.author]
  name = 'Ensono Digital'

